defmodule AshGeo.Test.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:geom, :geometry)
      add(:geom_within, :geometry)
    end

    create table(:geoms, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:geom, :"geometry(geometry,4326)")
    end

    create table(:constraints, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:geom, :geometry)
    end
  end

  def down do
    drop(table(:constraints))

    drop(table(:geoms))

    drop(table(:validations))
  end
end
